export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const HANDLE_REQUEST_POSTS_ERROR = 'HANDLE_REQUEST_POSTS_ERROR'

export const REQUEST_USERS = 'REQUEST_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const HANDLE_REQUEST_USERS_ERROR = 'HANDLE_REQUEST_USERS_ERROR'
